import './sass/index.scss'
import 'font-awesome/scss/font-awesome.scss'
import '@fortawesome/free-brands-svg-icons'
import '@fortawesome/free-regular-svg-icons'
import '@fortawesome/free-solid-svg-icons'